SD15_WORKFLOW = "LOCAL_TXT2IMG"
SD15_LLM_WORKFLOW = "LOCAL_TXT2IMG_LLM"
SD15_ALTS_WORKFLOW = "LOCAL_IMG2IMG"
SD15_DETAIL_WORKFLOW = "LOCAL_IMG2IMG"
UPSCALE_WORKFLOW = "LOCAL_UPSCALE"

SDXL_WORKFLOW = "LOCAL_TXT2IMG_SDXL"
SDXL_LLM_WORKFLOW = "LOCAL_TXT2IMG_LLM_SDXL"
SDXL_ALTS_WORKFLOW = "LOCAL_IMG2IMG_SDXL"
SDXL_DETAIL_WORKFLOW = "LOCAL_DETAIL_SDXL"
SDXL_UPSCALE_WORKFLOW = "LOCAL_UPSCALE_SDXL"

VIDEO_WORKFLOW = "LOCAL_TXT2VID"
