SD15_WORKFLOW = "LOCAL_TXT2IMG"
SD15_LLM_WORKFLOW = "LOCAL_TXT2IMG_LLM"
SD15_ALTS_WORKFLOW = "LOCAL_IMG2IMG"
SD15_DETAIL_WORKFLOW = "LOCAL_IMG2IMG"
UPSCALE_WORKFLOW = "LOCAL_UPSCALE"
SD15_INPAINT_WORKFLOW = "LOCAL_INPAINTING"

SDXL_WORKFLOW = "LOCAL_TXT2IMG_SDXL"
SDXL_LLM_WORKFLOW = "LOCAL_TXT2IMG_LLM_SDXL"
SDXL_ALTS_WORKFLOW = "LOCAL_IMG2IMG_SDXL"
SDXL_DETAIL_WORKFLOW = "LOCAL_DETAIL_SDXL"
SDXL_UPSCALE_WORKFLOW = "LOCAL_UPSCALE_SDXL"
SDXL_INPAINT_WORKFLOW = "LOCAL_INPAINTING_SDXL"

CASCADE_WORKFLOW = "LOCAL_CASCADE"

VIDEO_WORKFLOW = "LOCAL_TXT2VID"

MUSIC_WORKFLOW = "LOCAL_MUSICGEN"
MUSIC_CONTINUE_WORKFLOW = "LOCAL_MUSICGEN_CONTINUE"

TORTOISE_WORKFLOW = "LOCAL_TORTOISE"

MAX_STEPS = 30
MAX_CFG = 100.0
